#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

arch="$(podman system info --format json | jq -r '.host.arch')"
container_image="$(./unbase_oci --print-container-image)"

while [ $# -gt 0 ]; do
	case "$1" in
		--arch)
			arch="$2"
			shift 2
			;;
		--container-image)
			container_image="$2"
			shift 2
			;;
		*)
			break
			;;
	esac
done

for i in example/*; do
	"$i/run_example" --arch "$arch" --container-image "$container_image"
done
