#!/usr/bin/env bash

set -euo pipefail

while [ $# -gt 0 ]; do
	case "$1" in
		--arch)
			arch="$2"
			shift 2
			;;
		--os)
			os="$2"
			shift 2
			;;
		--config)
			config="$2"
			shift 2
			;;
		*)
			break
			;;
	esac
done

input="$(realpath "$1")"
output="$(realpath "$2")"

dir="$(mktemp -d)"
pushd "$dir" > /dev/null

mkdir -p blobs/sha256

rootfs_sha256="$(sha256sum < "$input" | head -c 64)"

gzip < "$input" > layer
layer_sha256="$(sha256sum < layer | head -c 64)"
layer_size="$(stat -c '%s' layer)"
mv layer "blobs/sha256/$layer_sha256"

cat > config << EOF
{
  "architecture": "$arch",
  "os": "$os",
  "config": $(sed '2,$s/^/  /' "$config"),
  "rootfs": {
    "type": "layers",
    "diff_ids": [
      "sha256:$rootfs_sha256"
    ]
  }
}
EOF

config_sha256="$(sha256sum < config | head -c 64)"
config_size="$(stat -c '%s' config)"
mv config "blobs/sha256/$config_sha256"

cat > manifest << EOF
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.oci.image.manifest.v1+json",
  "config": {
    "mediaType": "application/vnd.oci.image.config.v1+json",
    "digest": "sha256:$config_sha256",
    "size": $config_size
  },
  "layers": [
    {
      "mediaType": "application/vnd.oci.image.layer.v1.tar+gzip",
      "digest": "sha256:$layer_sha256",
      "size": $layer_size
    }
  ]
}
EOF

manifest_sha256="$(sha256sum < manifest | head -c 64)"
manifest_size="$(stat -c '%s' manifest)"
mv manifest "blobs/sha256/$manifest_sha256"

cat > index.json << EOF
{
  "schemaVersion": 2,
  "manifests": [
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "digest": "sha256:$manifest_sha256",
      "size": $manifest_size
    }
  ]
}
EOF

cat > oci-layout << EOF
{
  "imageLayoutVersion": "1.0.0"
}
EOF

tar --create --format posix --mtime '@0' --sort name --owner 0 --group 0 --numeric-owner --pax-option 'exthdr.name=%d/PaxHeaders/%f,delete=atime,delete=ctime' blobs index.json oci-layout > "$output"

popd > /dev/null
rm -rf "$dir"
