#!/usr/bin/env bash

set -eufo pipefail

oci="$1"

if [ "$(jq -r '.manifests | length' < "$oci/index.json")" != 1 ]; then
	echo "error: oci index with multiple manifests not supported" >&2
	exit 1
fi

manifest_digest="$(jq -r '.manifests[0].digest' < "$oci/index.json")"
config_digest="$(jq -r '.config.digest' < "$oci/blobs/sha256/${manifest_digest#sha256:}")"

echo "$oci/blobs/sha256/${config_digest#sha256:}"
